package beans.model;
// default package
// Generated 08-dic-2018 17:21:26 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Alergenos generated by hbm2java
 */
@Entity
@Table(name = "ALERGENOS", catalog = "quilicuabd")
public class Alergenos implements java.io.Serializable {

	private Integer alergenosPk;
	private String nombre;
	private String borrado;
	private Set<RelAlergenosMateriasPrimas> relAlergenosMateriasPrimases = new HashSet<RelAlergenosMateriasPrimas>(0);

	public Alergenos() {
	}

	public Alergenos(String nombre, String borrado) {
		this.nombre = nombre;
		this.borrado = borrado;
	}

	public Alergenos(String nombre, String borrado, Set<RelAlergenosMateriasPrimas> relAlergenosMateriasPrimases) {
		this.nombre = nombre;
		this.borrado = borrado;
		this.relAlergenosMateriasPrimases = relAlergenosMateriasPrimases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ALERGENOS_PK", unique = true, nullable = false)
	public Integer getAlergenosPk() {
		return this.alergenosPk;
	}

	public void setAlergenosPk(Integer alergenosPk) {
		this.alergenosPk = alergenosPk;
	}

	@Column(name = "NOMBRE", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "BORRADO", nullable = false, length = 1)
	public String getBorrado() {
		return this.borrado;
	}

	public void setBorrado(String borrado) {
		this.borrado = borrado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "alergenos")
	public Set<RelAlergenosMateriasPrimas> getRelAlergenosMateriasPrimases() {
		return this.relAlergenosMateriasPrimases;
	}

	public void setRelAlergenosMateriasPrimases(Set<RelAlergenosMateriasPrimas> relAlergenosMateriasPrimases) {
		this.relAlergenosMateriasPrimases = relAlergenosMateriasPrimases;
	}

}
