package beans.model;
// default package
// Generated 08-dic-2018 17:21:26 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatConservaciones generated by hbm2java
 */
@Entity
@Table(name = "CAT_CONSERVACIONES", catalog = "quilicuabd")
public class CatConservaciones implements java.io.Serializable {

	private Integer catConservacionesPk;
	private String nombre;
	private String borrado;
	private Set<Elaboraciones> elaboracioneses = new HashSet<Elaboraciones>(0);

	public CatConservaciones() {
	}

	public CatConservaciones(String nombre, String borrado) {
		this.nombre = nombre;
		this.borrado = borrado;
	}

	public CatConservaciones(String nombre, String borrado, Set<Elaboraciones> elaboracioneses) {
		this.nombre = nombre;
		this.borrado = borrado;
		this.elaboracioneses = elaboracioneses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CAT_CONSERVACIONES_PK", unique = true, nullable = false)
	public Integer getCatConservacionesPk() {
		return this.catConservacionesPk;
	}

	public void setCatConservacionesPk(Integer catConservacionesPk) {
		this.catConservacionesPk = catConservacionesPk;
	}

	@Column(name = "NOMBRE", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "BORRADO", nullable = false, length = 1)
	public String getBorrado() {
		return this.borrado;
	}

	public void setBorrado(String borrado) {
		this.borrado = borrado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catConservaciones")
	public Set<Elaboraciones> getElaboracioneses() {
		return this.elaboracioneses;
	}

	public void setElaboracioneses(Set<Elaboraciones> elaboracioneses) {
		this.elaboracioneses = elaboracioneses;
	}

}
