package beans.model;
// default package
// Generated 08-dic-2018 17:21:26 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatConservaciones generated by hbm2java
 */
@Entity
@Table(name = "CAT_TIPO_MENAJE", catalog = "quilicuabd")
public class CatTipoMenaje implements java.io.Serializable {

	private Integer catTipoMenajePk;
	private String nombre;
	private String borrado;
	private Set<Menaje> menaje = new HashSet<Menaje>(0);

	public CatTipoMenaje() {
	}

	public CatTipoMenaje(String nombre, String borrado) {
		this.nombre = nombre;
		this.borrado = borrado;
	}

	public CatTipoMenaje(String nombre, String borrado, Set<Menaje> menaje) {
		this.nombre = nombre;
		this.borrado = borrado;
		this.menaje = menaje;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CAT_TIPO_MENAJE_PK", unique = true, nullable = false)
	public Integer getCatTipoMenajePk() {
		return this.catTipoMenajePk;
	}

	public void setCatTipoMenajePk(Integer catTipoMenajePk) {
		this.catTipoMenajePk = catTipoMenajePk;
	}

	@Column(name = "NOMBRE", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "BORRADO", nullable = false, length = 1)
	public String getBorrado() {
		return this.borrado;
	}

	public void setBorrado(String borrado) {
		this.borrado = borrado;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catTipoMenaje")
//	public Set<Menaje> getMenaje() {
//		return this.menaje;
//	}
//
//	public void setMenaje(Set<Menaje> menaje) {
//		this.menaje = menaje;
//	}

}
