package beans.model;
// default package
// Generated 08-dic-2018 17:21:26 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Elaboraciones generated by hbm2java
 */
@Entity
@Table(name = "ELABORACIONES", catalog = "quilicuabd")
public class Elaboraciones implements java.io.Serializable {

	private Integer elaboracionesPk;
	private CatConservaciones catConservaciones;
	private String nombre;
	private String borrado;
	private Set<RelPuestosElaboraciones> relPuestosElaboracioneses = new HashSet<RelPuestosElaboraciones>(0);
	private Set<RelElaboracionesMateriasPrimas> relElaboracionesMateriasPrimases = new HashSet<RelElaboracionesMateriasPrimas>(
			0);
	private Set<RelPlatosElaboraciones> relPlatosElaboracioneses = new HashSet<RelPlatosElaboraciones>(0);

	public Elaboraciones() {
	}

	public Elaboraciones(String nombre, String borrado) {
		this.nombre = nombre;
		this.borrado = borrado;
	}

	public Elaboraciones(CatConservaciones catConservaciones, String nombre, String borrado,
			Set<RelPuestosElaboraciones> relPuestosElaboracioneses,
			Set<RelElaboracionesMateriasPrimas> relElaboracionesMateriasPrimases,
			Set<RelPlatosElaboraciones> relPlatosElaboracioneses) {
		this.catConservaciones = catConservaciones;
		this.nombre = nombre;
		this.borrado = borrado;
		this.relPuestosElaboracioneses = relPuestosElaboracioneses;
		this.relElaboracionesMateriasPrimases = relElaboracionesMateriasPrimases;
		this.relPlatosElaboracioneses = relPlatosElaboracioneses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ELABORACIONES_PK", unique = true, nullable = false)
	public Integer getElaboracionesPk() {
		return this.elaboracionesPk;
	}

	public void setElaboracionesPk(Integer elaboracionesPk) {
		this.elaboracionesPk = elaboracionesPk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CONSERVACION")
	public CatConservaciones getCatConservaciones() {
		return this.catConservaciones;
	}

	public void setCatConservaciones(CatConservaciones catConservaciones) {
		this.catConservaciones = catConservaciones;
	}

	@Column(name = "NOMBRE", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "BORRADO", nullable = false, length = 1)
	public String getBorrado() {
		return this.borrado;
	}

	public void setBorrado(String borrado) {
		this.borrado = borrado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "elaboraciones")
	public Set<RelPuestosElaboraciones> getRelPuestosElaboracioneses() {
		return this.relPuestosElaboracioneses;
	}

	public void setRelPuestosElaboracioneses(Set<RelPuestosElaboraciones> relPuestosElaboracioneses) {
		this.relPuestosElaboracioneses = relPuestosElaboracioneses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "elaboraciones")
	public Set<RelElaboracionesMateriasPrimas> getRelElaboracionesMateriasPrimases() {
		return this.relElaboracionesMateriasPrimases;
	}

	public void setRelElaboracionesMateriasPrimases(
			Set<RelElaboracionesMateriasPrimas> relElaboracionesMateriasPrimases) {
		this.relElaboracionesMateriasPrimases = relElaboracionesMateriasPrimases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "elaboraciones")
	public Set<RelPlatosElaboraciones> getRelPlatosElaboracioneses() {
		return this.relPlatosElaboracioneses;
	}

	public void setRelPlatosElaboracioneses(Set<RelPlatosElaboraciones> relPlatosElaboracioneses) {
		this.relPlatosElaboracioneses = relPlatosElaboracioneses;
	}

}
