package beans.model;
// default package
// Generated 08-dic-2018 17:21:26 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Evento generated by hbm2java
 */
@Entity
@Table(name = "EVENTO", catalog = "quilicuabd")
public class Evento implements java.io.Serializable {

	private Integer eventoPk;
	private Fincas fincas;
	private String nombre;
	private Date fecha;
	private String borrado;
	private String observaciones;
	private int invAdultos;
	private int invInfantil;
	private int invStaff;
	private Integer invTotal;
	private String responsable;
	private Set<RelEventoPlatos> relEventoPlatoses = new HashSet<RelEventoPlatos>(0);
	private Set<RelEventoMenaje> relEventoMenajes = new HashSet<RelEventoMenaje>(0);
	private Set<RelEventoPuestos> relEventoPuestoses = new HashSet<RelEventoPuestos>(0);

	public Evento() {
	}

	public Evento(String nombre, Date fecha, String borrado, int invAdultos, int invInfantil, int invStaff) {
		this.nombre = nombre;
		this.fecha = fecha;
		this.borrado = borrado;
		this.invAdultos = invAdultos;
		this.invInfantil = invInfantil;
		this.invStaff = invStaff;
	}

	public Evento(Fincas fincas, String nombre, Date fecha, String borrado, String observaciones, int invAdultos,
			int invInfantil, int invStaff, Integer invTotal, String responsable, Set<RelEventoPlatos> relEventoPlatoses,
			Set<RelEventoMenaje> relEventoMenajes, Set<RelEventoPuestos> relEventoPuestoses) {
		this.fincas = fincas;
		this.nombre = nombre;
		this.fecha = fecha;
		this.borrado = borrado;
		this.observaciones = observaciones;
		this.invAdultos = invAdultos;
		this.invInfantil = invInfantil;
		this.invStaff = invStaff;
		this.invTotal = invTotal;
		this.responsable = responsable;
		this.relEventoPlatoses = relEventoPlatoses;
		this.relEventoMenajes = relEventoMenajes;
		this.relEventoPuestoses = relEventoPuestoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EVENTO_PK", unique = true, nullable = false)
	public Integer getEventoPk() {
		return this.eventoPk;
	}

	public void setEventoPk(Integer eventoPk) {
		this.eventoPk = eventoPk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FINCA")
	public Fincas getFincas() {
		return this.fincas;
	}

	public void setFincas(Fincas fincas) {
		this.fincas = fincas;
	}

	@Column(name = "NOMBRE", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "BORRADO", nullable = false, length = 1)
	public String getBorrado() {
		return this.borrado;
	}

	public void setBorrado(String borrado) {
		this.borrado = borrado;
	}

	@Column(name = "OBSERVACIONES", length = 1000)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "INV_ADULTOS", nullable = false)
	public int getInvAdultos() {
		return this.invAdultos;
	}

	public void setInvAdultos(int invAdultos) {
		this.invAdultos = invAdultos;
	}

	@Column(name = "INV_INFANTIL", nullable = false)
	public int getInvInfantil() {
		return this.invInfantil;
	}

	public void setInvInfantil(int invInfantil) {
		this.invInfantil = invInfantil;
	}

	@Column(name = "INV_STAFF", nullable = false)
	public int getInvStaff() {
		return this.invStaff;
	}

	public void setInvStaff(int invStaff) {
		this.invStaff = invStaff;
	}

	@Column(name = "INV_TOTAL")
	public Integer getInvTotal() {
		return this.invTotal;
	}

	public void setInvTotal(Integer invTotal) {
		this.invTotal = invTotal;
	}

	@Column(name = "RESPONSABLE", length = 45)
	public String getResponsable() {
		return this.responsable;
	}

	public void setResponsable(String responsable) {
		this.responsable = responsable;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "evento")
	public Set<RelEventoPlatos> getRelEventoPlatoses() {
		return this.relEventoPlatoses;
	}

	public void setRelEventoPlatoses(Set<RelEventoPlatos> relEventoPlatoses) {
		this.relEventoPlatoses = relEventoPlatoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "evento")
	public Set<RelEventoMenaje> getRelEventoMenajes() {
		return this.relEventoMenajes;
	}

	public void setRelEventoMenajes(Set<RelEventoMenaje> relEventoMenajes) {
		this.relEventoMenajes = relEventoMenajes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "evento")
	public Set<RelEventoPuestos> getRelEventoPuestoses() {
		return this.relEventoPuestoses;
	}

	public void setRelEventoPuestoses(Set<RelEventoPuestos> relEventoPuestoses) {
		this.relEventoPuestoses = relEventoPuestoses;
	}

}
