package beans.model;
// default package
// Generated 08-dic-2018 17:21:26 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Fincas generated by hbm2java
 */
@Entity
@Table(name = "FINCAS", catalog = "quilicuabd")
public class Fincas implements java.io.Serializable {

	private Integer fincasPk;
	private String nombre;
	private String borrado;
	private String direccion;
	private Set<Evento> eventos = new HashSet<Evento>(0);

	public Fincas() {
	}

	public Fincas(String nombre, String borrado) {
		this.nombre = nombre;
		this.borrado = borrado;
	}

	public Fincas(String nombre, String borrado, String direccion, Set<Evento> eventos) {
		this.nombre = nombre;
		this.borrado = borrado;
		this.direccion = direccion;
		this.eventos = eventos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "FINCAS_PK", unique = true, nullable = false)
	public Integer getFincasPk() {
		return this.fincasPk;
	}

	public void setFincasPk(Integer fincasPk) {
		this.fincasPk = fincasPk;
	}

	@Column(name = "NOMBRE", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "BORRADO", nullable = false, length = 1)
	public String getBorrado() {
		return this.borrado;
	}

	public void setBorrado(String borrado) {
		this.borrado = borrado;
	}

	@Column(name = "DIRECCION", length = 200)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fincas")
	public Set<Evento> getEventos() {
		return this.eventos;
	}

	public void setEventos(Set<Evento> eventos) {
		this.eventos = eventos;
	}

}
