package beans.model;
// default package
// Generated 08-dic-2018 17:21:26 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Maquinaria generated by hbm2java
 */
@Entity
@Table(name = "MAQUINARIA", catalog = "quilicuabd")
public class Maquinaria implements java.io.Serializable {

	private int maquinariaPk;
	private MateriasPrimas materiasPrimas;
	private String nombre;
	private String borrado;
	private Set<RelPuestosMaquinaria> relPuestosMaquinarias = new HashSet<RelPuestosMaquinaria>(0);
	private Set<RelPlatosMaquinaria> relPlatosMaquinarias = new HashSet<RelPlatosMaquinaria>(0);

	public Maquinaria() {
	}

	public Maquinaria(int maquinariaPk, String nombre, String borrado) {
		this.maquinariaPk = maquinariaPk;
		this.nombre = nombre;
		this.borrado = borrado;
	}

	public Maquinaria(int maquinariaPk, MateriasPrimas materiasPrimas, String nombre, String borrado,
			Set<RelPuestosMaquinaria> relPuestosMaquinarias, Set<RelPlatosMaquinaria> relPlatosMaquinarias) {
		this.maquinariaPk = maquinariaPk;
		this.materiasPrimas = materiasPrimas;
		this.nombre = nombre;
		this.borrado = borrado;
		this.relPuestosMaquinarias = relPuestosMaquinarias;
		this.relPlatosMaquinarias = relPlatosMaquinarias;
	}

	@Id
	@Column(name = "MAQUINARIA_PK", unique = true, nullable = false)
	public int getMaquinariaPk() {
		return this.maquinariaPk;
	}

	public void setMaquinariaPk(int maquinariaPk) {
		this.maquinariaPk = maquinariaPk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEPENDENCIA_FK")
	public MateriasPrimas getMateriasPrimas() {
		return this.materiasPrimas;
	}
	

	public void setMateriasPrimas(MateriasPrimas materiasPrimas) {
		this.materiasPrimas = materiasPrimas;
	}

	@Column(name = "NOMBRE", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "BORRADO", nullable = false, length = 1)
	public String getBorrado() {
		return this.borrado;
	}

	public void setBorrado(String borrado) {
		this.borrado = borrado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "maquinaria")
	public Set<RelPuestosMaquinaria> getRelPuestosMaquinarias() {
		return this.relPuestosMaquinarias;
	}

	public void setRelPuestosMaquinarias(Set<RelPuestosMaquinaria> relPuestosMaquinarias) {
		this.relPuestosMaquinarias = relPuestosMaquinarias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "maquinaria")
	public Set<RelPlatosMaquinaria> getRelPlatosMaquinarias() {
		return this.relPlatosMaquinarias;
	}

	public void setRelPlatosMaquinarias(Set<RelPlatosMaquinaria> relPlatosMaquinarias) {
		this.relPlatosMaquinarias = relPlatosMaquinarias;
	}

}
