package beans.model;
// default package
// Generated 08-dic-2018 17:21:26 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MateriasPrimas generated by hbm2java
 */
@Entity
@Table(name = "MATERIAS_PRIMAS", catalog = "quilicuabd")
public class MateriasPrimas implements java.io.Serializable {

	private Integer materiasPrimasPk;
	private String nombre;
	private String borrado;
	private Set<Maquinaria> maquinarias = new HashSet<Maquinaria>(0);
	private Set<RelElaboracionesMateriasPrimas> relElaboracionesMateriasPrimases = new HashSet<RelElaboracionesMateriasPrimas>(
			0);
	private Set<RelAlergenosMateriasPrimas> relAlergenosMateriasPrimases = new HashSet<RelAlergenosMateriasPrimas>(0);

	public MateriasPrimas() {
	}

	public MateriasPrimas(String nombre, String borrado) {
		this.nombre = nombre;
		this.borrado = borrado;
	}

	public MateriasPrimas(String nombre, String borrado, Set<Maquinaria> maquinarias,
			Set<RelElaboracionesMateriasPrimas> relElaboracionesMateriasPrimases,
			Set<RelAlergenosMateriasPrimas> relAlergenosMateriasPrimases) {
		this.nombre = nombre;
		this.borrado = borrado;
		this.maquinarias = maquinarias;
		this.relElaboracionesMateriasPrimases = relElaboracionesMateriasPrimases;
		this.relAlergenosMateriasPrimases = relAlergenosMateriasPrimases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MATERIAS_PRIMAS_PK", unique = true, nullable = false)
	public Integer getMateriasPrimasPk() {
		return this.materiasPrimasPk;
	}

	public void setMateriasPrimasPk(Integer materiasPrimasPk) {
		this.materiasPrimasPk = materiasPrimasPk;
	}

	@Column(name = "NOMBRE", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "BORRADO", nullable = false, length = 1)
	public String getBorrado() {
		return this.borrado;
	}

	public void setBorrado(String borrado) {
		this.borrado = borrado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materiasPrimas")
	public Set<Maquinaria> getMaquinarias() {
		return this.maquinarias;
	}

	public void setMaquinarias(Set<Maquinaria> maquinarias) {
		this.maquinarias = maquinarias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materiasPrimas")
	public Set<RelElaboracionesMateriasPrimas> getRelElaboracionesMateriasPrimases() {
		return this.relElaboracionesMateriasPrimases;
	}

	public void setRelElaboracionesMateriasPrimases(
			Set<RelElaboracionesMateriasPrimas> relElaboracionesMateriasPrimases) {
		this.relElaboracionesMateriasPrimases = relElaboracionesMateriasPrimases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materiasPrimas")
	public Set<RelAlergenosMateriasPrimas> getRelAlergenosMateriasPrimases() {
		return this.relAlergenosMateriasPrimases;
	}

	public void setRelAlergenosMateriasPrimases(Set<RelAlergenosMateriasPrimas> relAlergenosMateriasPrimases) {
		this.relAlergenosMateriasPrimases = relAlergenosMateriasPrimases;
	}

}
