package beans.model;
// default package
// Generated 08-dic-2018 17:21:26 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Platos generated by hbm2java
 */
@Entity
@Table(name = "PLATOS", catalog = "quilicuabd")
public class Platos implements java.io.Serializable {

	private Integer platosPk;
	private CatTipoPlato catTipoPlato;
	private String nombre;
	private String borrado;
	private Set<RelPlatosElaboraciones> relPlatosElaboracioneses = new HashSet<RelPlatosElaboraciones>(0);
	private Set<RelPlatosMenaje> relPlatosMenajes = new HashSet<RelPlatosMenaje>(0);
	private Set<RelEventoPlatos> relEventoPlatoses = new HashSet<RelEventoPlatos>(0);
	private Set<RelPlatosMaquinaria> relPlatosMaquinarias = new HashSet<RelPlatosMaquinaria>(0);

	public Platos() {
	}

	public Platos(CatTipoPlato catTipoPlato, String nombre, String borrado) {
		this.catTipoPlato = catTipoPlato;
		this.nombre = nombre;
		this.borrado = borrado;
	}

	public Platos(CatTipoPlato catTipoPlato, String nombre, String borrado,
			Set<RelPlatosElaboraciones> relPlatosElaboracioneses, Set<RelPlatosMenaje> relPlatosMenajes,
			Set<RelEventoPlatos> relEventoPlatoses, Set<RelPlatosMaquinaria> relPlatosMaquinarias) {
		this.catTipoPlato = catTipoPlato;
		this.nombre = nombre;
		this.borrado = borrado;
		this.relPlatosElaboracioneses = relPlatosElaboracioneses;
		this.relPlatosMenajes = relPlatosMenajes;
		this.relEventoPlatoses = relEventoPlatoses;
		this.relPlatosMaquinarias = relPlatosMaquinarias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PLATOS_PK", unique = true, nullable = false)
	public Integer getPlatosPk() {
		return this.platosPk;
	}

	public void setPlatosPk(Integer platosPk) {
		this.platosPk = platosPk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIPO_FK", nullable = false)
	public CatTipoPlato getCatTipoPlato() {
		return this.catTipoPlato;
	}

	public void setCatTipoPlato(CatTipoPlato catTipoPlato) {
		this.catTipoPlato = catTipoPlato;
	}

	@Column(name = "NOMBRE", nullable = false, length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "BORRADO", nullable = false, length = 45)
	public String getBorrado() {
		return this.borrado;
	}

	public void setBorrado(String borrado) {
		this.borrado = borrado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "platos")
	public Set<RelPlatosElaboraciones> getRelPlatosElaboracioneses() {
		return this.relPlatosElaboracioneses;
	}

	public void setRelPlatosElaboracioneses(Set<RelPlatosElaboraciones> relPlatosElaboracioneses) {
		this.relPlatosElaboracioneses = relPlatosElaboracioneses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "platos")
	public Set<RelPlatosMenaje> getRelPlatosMenajes() {
		return this.relPlatosMenajes;
	}

	public void setRelPlatosMenajes(Set<RelPlatosMenaje> relPlatosMenajes) {
		this.relPlatosMenajes = relPlatosMenajes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "platos")
	public Set<RelEventoPlatos> getRelEventoPlatoses() {
		return this.relEventoPlatoses;
	}

	public void setRelEventoPlatoses(Set<RelEventoPlatos> relEventoPlatoses) {
		this.relEventoPlatoses = relEventoPlatoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "platos")
	public Set<RelPlatosMaquinaria> getRelPlatosMaquinarias() {
		return this.relPlatosMaquinarias;
	}

	public void setRelPlatosMaquinarias(Set<RelPlatosMaquinaria> relPlatosMaquinarias) {
		this.relPlatosMaquinarias = relPlatosMaquinarias;
	}

}
