package beans.model;
// default package
// Generated 08-dic-2018 17:21:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Proporciones generated by hbm2java
 */
@Entity
@Table(name = "PROPORCIONES", catalog = "quilicuabd")
public class Proporciones implements java.io.Serializable {

	private Integer proporcionesPk;
	private String nombre;
	private float valor;
	private String borrado;

	public Proporciones() {
	}

	public Proporciones(String nombre, float valor, String borrado) {
		this.nombre = nombre;
		this.valor = valor;
		this.borrado = borrado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PROPORCIONES_PK", unique = true, nullable = false)
	public Integer getProporcionesPk() {
		return this.proporcionesPk;
	}

	public void setProporcionesPk(Integer proporcionesPk) {
		this.proporcionesPk = proporcionesPk;
	}

	@Column(name = "NOMBRE", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "VALOR", nullable = false, precision = 12, scale = 0)
	public float getValor() {
		return this.valor;
	}

	public void setValor(float valor) {
		this.valor = valor;
	}

	@Column(name = "BORRADO", nullable = false, length = 1)
	public String getBorrado() {
		return this.borrado;
	}

	public void setBorrado(String borrado) {
		this.borrado = borrado;
	}

}
