package beans.model;
// default package
// Generated 08-dic-2018 17:21:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RelAlergenosMateriasPrimas generated by hbm2java
 */
@Entity
@Table(name = "REL_ALERGENOS_MATERIAS_PRIMAS", catalog = "quilicuabd")
public class RelAlergenosMateriasPrimas implements java.io.Serializable {

	private Integer relAlergenosMateriasPrimasPk;
	private Alergenos alergenos;
	private MateriasPrimas materiasPrimas;
	private String borrado;

	public RelAlergenosMateriasPrimas() {
	}

	public RelAlergenosMateriasPrimas(Alergenos alergenos, MateriasPrimas materiasPrimas, String borrado) {
		this.alergenos = alergenos;
		this.materiasPrimas = materiasPrimas;
		this.borrado = borrado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "REL_ALERGENOS_MATERIAS_PRIMAS_PK", unique = true, nullable = false)
	public Integer getRelAlergenosMateriasPrimasPk() {
		return this.relAlergenosMateriasPrimasPk;
	}

	public void setRelAlergenosMateriasPrimasPk(Integer relAlergenosMateriasPrimasPk) {
		this.relAlergenosMateriasPrimasPk = relAlergenosMateriasPrimasPk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ALERGENO_FK", nullable = false)
	public Alergenos getAlergenos() {
		return this.alergenos;
	}

	public void setAlergenos(Alergenos alergenos) {
		this.alergenos = alergenos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MATERIA_PRIMAS_FK", nullable = false)
	public MateriasPrimas getMateriasPrimas() {
		return this.materiasPrimas;
	}

	public void setMateriasPrimas(MateriasPrimas materiasPrimas) {
		this.materiasPrimas = materiasPrimas;
	}

	@Column(name = "BORRADO", nullable = false, length = 1)
	public String getBorrado() {
		return this.borrado;
	}

	public void setBorrado(String borrado) {
		this.borrado = borrado;
	}

}
