package beans.model;
// default package
// Generated 08-dic-2018 17:21:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RelElaboracionesMateriasPrimas generated by hbm2java
 */
@Entity
@Table(name = "REL_ELABORACIONES_MATERIAS_PRIMAS", catalog = "quilicuabd")
public class RelElaboracionesMateriasPrimas implements java.io.Serializable {

	private Integer relElaboracionesMateriasPrimasPk;
	private Elaboraciones elaboraciones;
	private MateriasPrimas materiasPrimas;
	private String borrado;

	public RelElaboracionesMateriasPrimas() {
	}

	public RelElaboracionesMateriasPrimas(Elaboraciones elaboraciones, MateriasPrimas materiasPrimas, String borrado) {
		this.elaboraciones = elaboraciones;
		this.materiasPrimas = materiasPrimas;
		this.borrado = borrado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "REL_ELABORACIONES_MATERIAS_PRIMAS_PK", unique = true, nullable = false)
	public Integer getRelElaboracionesMateriasPrimasPk() {
		return this.relElaboracionesMateriasPrimasPk;
	}

	public void setRelElaboracionesMateriasPrimasPk(Integer relElaboracionesMateriasPrimasPk) {
		this.relElaboracionesMateriasPrimasPk = relElaboracionesMateriasPrimasPk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ELABORACIONES_FK", nullable = false)
	public Elaboraciones getElaboraciones() {
		return this.elaboraciones;
	}

	public void setElaboraciones(Elaboraciones elaboraciones) {
		this.elaboraciones = elaboraciones;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MATERIAS_PRIMAS_FK", nullable = false)
	public MateriasPrimas getMateriasPrimas() {
		return this.materiasPrimas;
	}

	public void setMateriasPrimas(MateriasPrimas materiasPrimas) {
		this.materiasPrimas = materiasPrimas;
	}

	@Column(name = "BORRADO", nullable = false, length = 1)
	public String getBorrado() {
		return this.borrado;
	}

	public void setBorrado(String borrado) {
		this.borrado = borrado;
	}

}
