package beans.model;
// default package
// Generated 08-dic-2018 17:21:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RelEventoPlatos generated by hbm2java
 */
@Entity
@Table(name = "REL_EVENTO_PLATOS", catalog = "quilicuabd")
public class RelEventoPlatos implements java.io.Serializable {

	private Integer relEventoPlatosPk;
	private Evento evento;
	private Platos platos;
	private String borrado;

	public RelEventoPlatos() {
	}

	public RelEventoPlatos(Evento evento, Platos platos, String borrado) {
		this.evento = evento;
		this.platos = platos;
		this.borrado = borrado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "REL_EVENTO_PLATOS_PK", unique = true, nullable = false)
	public Integer getRelEventoPlatosPk() {
		return this.relEventoPlatosPk;
	}

	public void setRelEventoPlatosPk(Integer relEventoPlatosPk) {
		this.relEventoPlatosPk = relEventoPlatosPk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EVENTO_FK", nullable = false)
	public Evento getEvento() {
		return this.evento;
	}

	public void setEvento(Evento evento) {
		this.evento = evento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PLATOS_FK", nullable = false)
	public Platos getPlatos() {
		return this.platos;
	}

	public void setPlatos(Platos platos) {
		this.platos = platos;
	}

	@Column(name = "BORRADO", nullable = false, length = 45)
	public String getBorrado() {
		return this.borrado;
	}

	public void setBorrado(String borrado) {
		this.borrado = borrado;
	}

}
