package beans.model;
// default package
// Generated 08-dic-2018 17:21:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RelPlatosMaquinaria generated by hbm2java
 */
@Entity
@Table(name = "REL_PLATOS_MAQUINARIA", catalog = "quilicuabd")
public class RelPlatosMaquinaria implements java.io.Serializable {

	private Integer relPlatosMaquinariaPk;
	private Maquinaria maquinaria;
	private Platos platos;
	private String borrado;
	private Float cantidad;

	public RelPlatosMaquinaria() {
	}

	public RelPlatosMaquinaria(Maquinaria maquinaria, Platos platos, String borrado) {
		this.maquinaria = maquinaria;
		this.platos = platos;
		this.borrado = borrado;
	}

	public RelPlatosMaquinaria(Maquinaria maquinaria, Platos platos, String borrado, Float cantidad) {
		this.maquinaria = maquinaria;
		this.platos = platos;
		this.borrado = borrado;
		this.cantidad = cantidad;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "REL_PLATOS_MAQUINARIA_PK", unique = true, nullable = false)
	public Integer getRelPlatosMaquinariaPk() {
		return this.relPlatosMaquinariaPk;
	}

	public void setRelPlatosMaquinariaPk(Integer relPlatosMaquinariaPk) {
		this.relPlatosMaquinariaPk = relPlatosMaquinariaPk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MAQUINARIA_FK", nullable = false)
	public Maquinaria getMaquinaria() {
		return this.maquinaria;
	}

	public void setMaquinaria(Maquinaria maquinaria) {
		this.maquinaria = maquinaria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PLATO_FK", nullable = false)
	public Platos getPlatos() {
		return this.platos;
	}

	public void setPlatos(Platos platos) {
		this.platos = platos;
	}

	@Column(name = "BORRADO", nullable = false, length = 1)
	public String getBorrado() {
		return this.borrado;
	}

	public void setBorrado(String borrado) {
		this.borrado = borrado;
	}

	@Column(name = "CANTIDAD", precision = 12, scale = 0)
	public Float getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Float cantidad) {
		this.cantidad = cantidad;
	}

}
