package beans.model;
// default package
// Generated 08-dic-2018 17:21:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RelPuestosMaquinaria generated by hbm2java
 */
@Entity
@Table(name = "REL_PUESTOS_MAQUINARIA", catalog = "quilicuabd")
public class RelPuestosMaquinaria implements java.io.Serializable {

	private Integer relPuestosMaquinariaPk;
	private Maquinaria maquinaria;
	private Puestos puestos;
	private String borrado;

	public RelPuestosMaquinaria() {
	}

	public RelPuestosMaquinaria(Maquinaria maquinaria, Puestos puestos, String borrado) {
		this.maquinaria = maquinaria;
		this.puestos = puestos;
		this.borrado = borrado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "REL_PUESTOS_MAQUINARIA_PK", unique = true, nullable = false)
	public Integer getRelPuestosMaquinariaPk() {
		return this.relPuestosMaquinariaPk;
	}

	public void setRelPuestosMaquinariaPk(Integer relPuestosMaquinariaPk) {
		this.relPuestosMaquinariaPk = relPuestosMaquinariaPk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MAQUINARIA_FK", nullable = false)
	public Maquinaria getMaquinaria() {
		return this.maquinaria;
	}

	public void setMaquinaria(Maquinaria maquinaria) {
		this.maquinaria = maquinaria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PUESTOS_FK", nullable = false)
	public Puestos getPuestos() {
		return this.puestos;
	}

	public void setPuestos(Puestos puestos) {
		this.puestos = puestos;
	}

	@Column(name = "BORRADO", nullable = false, length = 1)
	public String getBorrado() {
		return this.borrado;
	}

	public void setBorrado(String borrado) {
		this.borrado = borrado;
	}

}
