package beans.model;
// default package
// Generated 08-dic-2018 17:21:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RelPuestosElaboraciones generated by hbm2java
 */
@Entity
@Table(name = "REL_PUESTOS_ELABORACIONES", catalog = "quilicuabd")
public class RelPuestosElaboraciones implements java.io.Serializable {

	private Integer relPuestosElaboracionesPk;
	private Elaboraciones elaboraciones;
	private Puestos puestos;
	private String borrado;

	public RelPuestosElaboraciones() {
	}

	public RelPuestosElaboraciones(Elaboraciones elaboraciones, Puestos puestos, String borrado) {
		this.elaboraciones = elaboraciones;
		this.puestos = puestos;
		this.borrado = borrado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "REL_PUESTOS_ELABORACIONES_PK", unique = true, nullable = false)
	public Integer getRelPuestosElaboracionesPk() {
		return this.relPuestosElaboracionesPk;
	}

	public void setRelPuestosElaboracionesPk(Integer relPuestosElaboracionesPk) {
		this.relPuestosElaboracionesPk = relPuestosElaboracionesPk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ELABORACIONES", nullable = false)
	public Elaboraciones getElaboraciones() {
		return this.elaboraciones;
	}

	public void setElaboraciones(Elaboraciones elaboraciones) {
		this.elaboraciones = elaboraciones;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PUESTOS_FK", nullable = false)
	public Puestos getPuestos() {
		return this.puestos;
	}

	public void setPuestos(Puestos puestos) {
		this.puestos = puestos;
	}

	@Column(name = "BORRADO", nullable = false, length = 1)
	public String getBorrado() {
		return this.borrado;
	}

	public void setBorrado(String borrado) {
		this.borrado = borrado;
	}

}
